### ISSUE TITLE
Using TypeScript um Json auf Objekte zu "mappen"

### ISSUE THREAD

**Issue by idseefeld** [angular-buch/book-monkey2-api#2]
Ich bin kürzlich auf eine einfache Methode gestoßen, um Json auf eigene Objekttypen mit dem **as**-Operator zu "mappen". Ganz ohne RxJS.map und Factories:
Beispiel-Json:
example.json
```
{
  "title": "Complexes Objekt",
  "persons": 
  [
	{
		"id": 1,
		"name": "Max"
	},
	{
		"id": 2,
		"name": "Moritz"
	},
	{
		"id": 3,
		"name": "Widow Bolte"
	}
  ],
  "actions": 
  [
	{
		"id": 1,
		"description": "saw gap into bridge"
	},
	{
		"id": 2,
		"description": "steal grilled chicken"
	}
  ],
}
```

example.models.ts
```
export class Person {
  public id: number;
  public name: string;
}

export class Action {
  public id: number;
  public description: string;
}

export class Events {
  public title: string;
  public persons: Person[];
  public actions: Action[];
}
```

example.services.ts
```
import { Person, Action, ComplexObj } from '.model.ts';
...
@Injectable()
export class exampleService {
	...
	public readAll(): Observable<Events> {
		return this.http
		  .get('/Api/AllEvents/')
		  .retry(3)
		  .map(response => response.json() as Events)
		  .catch(this.errorHandler);
	}

```
Die interessante Teil ist: **.map(response => response.json() as Events)**

example.component.ts
```
...
src: exampleService;
ev: Events;
constructor(@Inject(exampleService) exampleServiceFactory: any) {
	this.src = exampleServiceFactory();
}
ngOnInit(){
	this.src.readAll().subscribe(res => this.ev = res);
}
```

Falls ich einen entsprechenden Hinweis nicht überlesen habe, hoffe ich, dass diese eine hilfreiche Anmerkung ist.

**Comment by fmalcher** [comment]
Hallo Dirk,

danke für deinen Beitrag! In Deinem Beispiel und auch für das Beispiel im Angular-Buch funktioniert der `as`-Operator praktisch sehr gut. Man muss damit allerdings sehr aufpassen: Das ist eine sogenannte *Type Assertion*, mit der einfach nur der Compiler ruhiggestellt wird.

Folgender Code ist gültig:

```ts
class Book {
  title: string;
  rating: number;

  rateUp() {
    this.rating++;
  }
}

const book = { rating: 3 } as Book;
```

Es knallt aber, sobald wir auf `title` oder gar `rateUp` zugreifen wollen:

```ts
book.rateUp()
const title = book.title;
```

TypeScript denkt, `book` wäre ein echtes, vollständiges `Book` – tatsächlich ist es aber nur das Objekt `{ rating: 3 }` und wir haben dem Typsystem vorgegaukelt, es wäre mehr.
Dieses Verhalten ist nützlich in Situationen, in denen man ganz genau abgrenzen kann, was man tut, z.B. in Tests. An allen anderen Stellen würde ich immer einen anderen Weg wählen.

Fehlende Eigenschaften (besonders die Methoden wie `rateUp()`) werden durch `as` niemals "eingebaut" und das kann zu schwerwiegenden Fehlern führen, wenn doch mal jemand diese Eigenschaften verwendet.
Nutzt man also Klassen für die Datenmodelle, muss man immer auch einen Konstruktor `new Book()` aufrufen, um eine Instanz zu erstellen.
Mit Interfaces wird das viel einfacher, dann reicht es, wenn ein Objekt die exakte vorgegebene Struktur besitzt und wir müssen keinen Konstruktor aufrufen. Nachteil: Die Models können dann keine Methoden mehr tragen. Tatsächlich empfiehlt der StyleGuide, Interfaces für die Datenmodelle zu verwenden:

> Consider using an interface for data models.
> (https://angular.io/guide/styleguide#style-03-03)

Der HttpClient hat für alle seine Methoden übrigens auch generische Typparameter:
```ts
return this.http.get<Book>('/Api/AllEvents/')
```

Hier ist auch Vorsicht geboten: Intern wird der Typ einfach zugewiesen, egal wie die Daten von der API tatsächlich strukturiert sind. Wenn Dein `Book` also genauso aussieht wie die API-Daten, ist alles schick. Hat `Book` noch mehr Eigenschaften oder gar Methoden, dann ist wieder ein Mapping nötig.
An der Stelle solltest Du dann *Data Transfer Objects*  bauen, die die Daten von der API beschreiben. Siehe dazu auch unser Artikel zum "neuen" HttpClient": https://angular-buch.com/blog/2017-11-httpclient

Ist zwar alles etwas mehr Arbeit, dafür hat man dann aber auch saubere Typen, die wirklich das halten, was sie versprechen! 😎

**Comment by idseefeld** [comment]
Hallo Ferdinand,
ganz herzlichen Dank für die unerwartet schnell und ausführliche Antwort!
Das macht die Thematik noch deutlicher. Und wo ich schon dabei bin - vielen Dank für das gute Buch auch an Deine Co-Autoren bzw. das ganz Team!
Viele Grüße
Dirk

**Comment by JohannesHoppe** [comment]
Bitte! :smile:
